# Generated by Django 5.0.6 on 2024-06-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='numBaths',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='numRooms',
            new_name='rooms',
        ),
    ]
