# Generated by Django 5.0.6 on 2024-06-09 01:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_listing_joinedlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='joinedListing',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, default=list, size=None),
        ),
    ]
