# Generated by Django 5.0.6 on 2024-06-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_listing_joinedlisting'),  # Replace 'previous_migration' with the actual previous migration name
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='joined',
        ),
    ]