# Generated by Django 5.0.6 on 2024-06-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_listing_joinedlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.PositiveIntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rent',
            field=models.PositiveIntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.PositiveIntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
