# Generated by Django 5.0.6 on 2024-06-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_listing_bathrooms_alter_listing_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='imageUrl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
