# Generated by Django 5.0.6 on 2024-06-30 22:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_listing_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None),
        ),
    ]
